### ISSUE TITLE
MiniZinc stopped with a non-zero exit code, but did not output an error message

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#156]
solver: minizinc's gecode, gist, restart and set subsolvers
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
minizinc-python release version 0.7.0 commit {https://github.com/MiniZinc/minizinc-python/commit/a195cf63fcfbc98665d70ab64efb5424db25bd7e)

Some MiniZinc subsolvers crash without an error message, while other solvers can solve the problem.

[minimized.zip](https://github.com/CPMpy/cpmpy/files/10002538/minimized.zip)

```python 
from cpmpy import *

file ="minimized"  # don't forget to unzip
m=Model().from_file(file)
m.solve(solver='minizinc:gecode') # same with "minizinc:gist", "minizinc:restart" and "minizinc:set"
```

expected behavior: 
No crash like other solvers ("minizinc:gurobi", "ortools" ...)

bug found while working on my master thesis.

**Comment by tias** [comment]
Can not reproduce?

￼
cpm_file = os.path.join(tmpdir, zipfnames[0])
m = Model().from_file(cpm_file)
print(m)
print_variables(m)
Constraints:
    s[1] == 0
    circuit(s[0],s[1],s[2],s[3],s[4],s[5],s[6],s[7],s[8],s[9],s[10],s[11],s[12],s[13],s[14])
Objective: None
Variables:
    s[1]: 0..14
    s[0]: 0..14
    s[2]: 0..14
    s[3]: 0..14
    s[4]: 0..14
    s[5]: 0..14
    s[6]: 0..14
    s[7]: 0..14
    s[8]: 0..14
    s[9]: 0..14
    s[10]: 0..14
    s[11]: 0..14
    s[12]: 0..14
    s[13]: 0..14
    s[14]: 0..14
In [9]:
￼
m.solve("minizinc:gecode")
Out[9]:
True


perhaps it is fixed as part of another fix, can you check with master on your system? (you can close if fixed)

**Comment by rubenkindt** [comment]
Unfortunately, even with a fresh install of CPMpy (both 0.9.9 and 0.9.10) and MiniZinc 0.7.0 I still get the errors with the same constraints and variables.

**Comment by Wout4** [comment]
I get a similar/same error with minizinc solvers. 
Do the tests in tests/solvers.py give the same error?

**Comment by rubenkindt** [comment]
Yes, in tests/test_solvers.py: test_installed_solvers, test_installed_solvers_solveAll and test_minizinc fail. with the first and last one giving the ```minizinc.error.MiniZincError: MiniZinc stopped with a non-zero exit code, but did not output an error message.``` and the second one giving a ```Exception: MiniZinc solver returned with status 'Error'```

**Comment by Wout4** [comment]
The error persists when I try to solve a model with minizinc python (not using CPMpy). So I think it is unrelated to CPMpy, which explains why others are having no issues.
Still don't know what causes it, I think it might have to do with the fact that minizinc uses asynchio

**Comment by Wout4** [comment]
The same issue was raised in minizinc-python: https://github.com/MiniZinc/minizinc-python/issues/60
Adding the minizinc folder to my PATH solved the issue for me.
(I am using windows)

**Comment by tias** [comment]
Is there a way we could catch this exception and output a warning wrt putting the minizinc folder in the PATH? If not, can close, if yes and small effort, could help others in the same situation
